### ISSUE TITLE
Date is undefined

### ISSUE THREAD

**Issue by dzdidi** [jonschlinkert/kind-of#23] opened 2018-03-28 07:46 UTC
```
<my package>/node_modules/nyc/node_modules/test-exclude/node_modules/kind-of/index.js:82
  if (val instanceof Date) return true;
                     ^

ReferenceError: Date is not defined
```
node version: `v7.10.1`
npm version: `4.2.0`
container image: `phusion/baseimage`

`x instanceof Date` works in the node console within the same container

**Comment by jonschlinkert** [comment] 2018-03-28 12:22
Given that `Date` was added in [the very first version of ECMAScript](https://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf), I'm assuming this is a bug related to the tool you're using. Closing since you didn't provide enough information to come to a different conclusion, but feel free to reopen if you can provide enough detail for anyone else to reproduce the bug.

**Closed by jonschlinkert** 2018-03-28 12:22 UTC
